#!/bin/bash
set -e

case "$1" in
    configure)
        # Update desktop database
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database -q /usr/share/applications || true
        fi
        
        # Update icon cache if icon is present
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -q -f /usr/share/icons/hicolor || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
